using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
// Import the models namespace to use the model classes
using DotNetGrillWebUI.Models;

namespace DotNetGrillWebUI.Data
{
    // Note: this class was generated by the project template
    // if you selected Authentication Type as Individual User Accounts when creating the project
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        // Add DbSet properties for each model class
        // This tells EF that I want to have a table in the DB that corresponds to a Model class
        // Names are pluralized by convention
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
    }
}
